### ISSUE TITLE
Adding the Newspaper Navigator Model

### ISSUE THREAD

**Issue by bcglee** [Layout-Parser/platform#14]
# Add new layout models or pipelines  

## Model Description 
The Newspaper Navigator visual content recognition model detects 7 different types of visual content on historic newspaper pages: photographs, illustrations, maps, comics, editorial cartoons, headlines, and advertisements. For more information, a paper describing the model's training and performance can be found [https://dl.acm.org/doi/10.1145/3340531.3412767](here), and the corresponding GitHub repository can be found [https://github.com/LibraryOfCongress/newspaper-navigator](here).

## Model Card Data 

```yaml
name: The Newspaper Navigator Visual Content Recognition Model
type: model
link: https://github.com/LibraryOfCongress/newspaper-navigator
doctype: historical, newspaper
description: Given an image of a historic newspaper page, this model predicts bounding boxes corresponding to the locations of photographs, illustrations, maps, comics, editorial cartoons, headlines, and advertisements.
config-names: # The Newspaper Navigator visual content recognition model is a finetuned R50-FPN backbone from Detectron2's Model Zoo ("faster_rcnn_R_50_FPN_3x").
- lp-model-config: lp://NewspaperNavigator/faster_rcnn_R_50_FPN_3x
  architecture: detectron2
  sizes: medium 
min-lp-version: 0.1.3
```
