### ISSUE TITLE
Release the HJDataset models 

### ISSUE THREAD

**Issue by lolipopshock** [Layout-Parser/platform#16]
# Add HJDataset Models 

## Model Card Data 

```yaml
name: HJDataset Models 
type: model
link: https://dell-research-harvard.github.io/HJDataset/
doctype: historical 
doclanguage: ja
description: 
config-names: 
- lp-model-config: lp://HJDataset/faster_rcnn_R_50_FPN_3x
  architecture: detectron2
  sizes: medium
- lp-model-config: lp://HJDataset/mask_rcnn_R_50_FPN_3x
  architecture: detectron2
  sizes: medium
- lp-model-config: lp://HJDataset/retinanet_R_50_FPN_3x
  architecture: detectron2
  sizes: medium
min-lp-version: 0.1
```
