### ISSUE TITLE
Release VILA 

### ISSUE THREAD

**Issue by lolipopshock** [Layout-Parser/platform#17]
# VILA: Incorporating VIsual LAyout Structures for Scientific Text Classification

## Model Description 

Scientific papers typically organize contents in visual groups like text blocks or lines, and text within each group usually have the same semantics. VILA method explores different approaches for injecting the group structure into the text classifiers, and improves the accuracy or efficiency of the scientific text classification task.

![](https://github.com/allenai/VILA/blob/master/.github/github-teaser.png)

## Model Card Data 

```yaml
name: VILA - Incorporating VIsual LAyout Structures for Scientific Text Classification
type: pipeline 
link: https://github.com/allenai/vila
doctype: scientific
doclanguage: en
```
