### ISSUE TITLE
Release PrimA Layout Models

### ISSUE THREAD

**Issue by lolipopshock** [Layout-Parser/platform#18]
# Release PrimA Layout Models

## Model Card Data 

```yaml
name: PrimA Layout Models
type: model
link: https://www.primaresearch.org/dataset/
doctype: scientific, business, magazine
doclanguage: en
description: 
config-names:
- lp-model-config: lp://PrimaLayout/mask_rcnn_R_50_FPN_3x
  architecture: detectron2
  sizes: medium
min-lp-version: 0.1
```
