### ISSUE TITLE
Release TableBank Models 

### ISSUE THREAD

**Issue by lolipopshock** [Layout-Parser/platform#19]
# Release TableBank Models 

## Model Card Data 

```yaml
name: TableBank Models
type: model
link: https://github.com/doc-analysis/TableBank
doctype: scientific, business
doclanguage: en, zh
description: 
config-names:
- lp-model-config: lp://TableBank/faster_rcnn_R_50_FPN_3x
  architecture: detectron2
  sizes: medium
- lp-model-config: lp://TableBank/faster_rcnn_R_101_FPN_3x
  architecture: detectron2
  sizes: large
- lp-model-config: lp://TableBank/ppyolov2_r50vd_dcn_365e
  architecture: paddledetection
  sizes: small
min-lp-version: 0.1.3
```
