### ISSUE TITLE
Release MFD Models 

### ISSUE THREAD

**Issue by lolipopshock** [Layout-Parser/platform#20]
# Release MFD Models 

## Model Card Data 
*Please fill in the model details following the instructions, such that your model can be rendered in the layout platform.*

```yaml
name: Math Formula Detection (MFD) Models
type: model
link: 
doctype: scientific
doclanguage: en
description: 
config-names: 
- lp-model-config: lp://MFD/faster_rcnn_R_50_FPN_3x
  architecture: detectron2
  sizes: medium
- lp-model-config: lp://MFD/tf_efficientdet_d0
  architecture: efficientdet
  sizes: tiny
- lp-model-config: lp://MFD/tf_efficientdet_d1
  architecture: efficientdet
  sizes: small
min-lp-version: 0.2.1
```
