### ISSUE TITLE
Release PubLayNet Models 

### ISSUE THREAD

**Issue by lolipopshock** [Layout-Parser/platform#5]
# Add new layout models or pipelines  

## Model Description 

PubLayNet Models are trained based on PubLayNet dataset, and they are used for detecting five different types of regions from scientific documents (paragraph, title, list, table, and figure). For example: 

```python
import layoutparser as lp
import cv2
image = cv2.imread("data/paper-image.jpg")[..., ::-1]
model = lp.Detectron2LayoutModel('lp://PubLayNet/faster_rcnn_R_50_FPN_3x/config',
                                 extra_config=["MODEL.ROI_HEADS.SCORE_THRESH_TEST", 0.8])
layout = model.detect(image)
lp.draw_box(image, layout, box_width=3, show_element_type=True)
```

<img src="https://layout-parser.readthedocs.io/en/latest/_images/output_7_0.png" alt="drawing" width="400"/>

## Model Card Data 

```yaml
name: PubLayNet Models
type: model
link: https://github.com/ibm-aur-nlp/PubLayNet
doctype: scientific
doclanguage: en
description: The model can detect five different types of regions from scientific documents (paragraph, title, list, table, and figure). 
config-names: 
- lp-model-config: lp://PubLayNet/faster_rcnn_R_50_FPN_3x
  architecture: detectron2
  sizes: medium 
- lp-model-name: lp://PubLayNet/mask_rcnn_X_101_32x8d_FPN_3x
  architecture: detectron2
  sizes: large
- lp-model-config: lp://PubLayNet/tf_efficientdet_d0
  architecture: efficientdet
  sizes: tiny
- lp-model-config: lp://PubLayNet/tf_efficientdet_d1
  architecture: efficientdet
  sizes: small 
- lp-model-config: lp://PubLayNet/ppyolov2_r50vd_dcn_365e
  architecture: paddledetection
  sizes: small 
min-lp-version: 0.1
```
