### ISSUE TITLE
Legal Docket Parser 

### ISSUE THREAD

**Issue by lolipopshock** [Layout-Parser/platform#6]
# Add new layout models or pipelines  

## Model Description 
An end-to-end pipeline that extracts the docket table and parses structured case metadata based on the layout and styles. 
![image](https://user-images.githubusercontent.com/22512825/131281121-356a5431-7de9-4c79-aa4f-2cbe22c7dabe.png)

## Model Card Data 

```yaml
name: Legal Docket Parser 
type: pipeline
link: https://github.com/allenai/pacer-docket-parser
doctype: legal, business
doclanguage: en
description: An end-to-end pipeline that extracts the docket table and parses structured case metadata based on the layout and styles. 
```
